apiVersion: v1
kind: Service
metadata:
  name: notes-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
spec:
  selector:
    app: notes-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
