apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: notes-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notes-frontend
                port:
                  number: 80
