apiVersion: v1
kind: Service
metadata:
  name: notes-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
spec:
  selector:
    app: notes-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
