apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notes-backend-role
  namespace: notes-app
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["backend-secret"]